language: rust
sudo: false

DEPLOY_TO_GITHUB: &DEPLOY_TO_GITHUB
  before_deploy:
    - git config --local user.name "Julien Duranleau"
    - git config --local user.email "julien.duranleau@hotmail.com"
    - name="inke-$TRAVIS_TAG-$TARGET"
    - mkdir $name
    - cp target/$TARGET/release/inke $name/
    - tar czvf $name.tar.gz $name
  deploy:
    provider: releases
    api_key: '$GITHUB_API_KEY'
    file: inke-$TRAVIS_TAG-$TARGET.tar.gz
    skip_cleanup: true
    on:
      branch: master
      tags: true

matrix:
  include:

  - name: Linux Binary
    env: TARGET=x86_64-unknown-linux-musl
    rust: stable
    before_script: rustup target add $TARGET
    script: cargo build --release --target $TARGET --locked --features vendored-openssl
    addons:
      apt:
        packages:
          - musl-tools
    <<: *DEPLOY_TO_GITHUB

  - name: macOS Binary
    env: MACOSX_DEPLOYMENT_TARGET=10.7 TARGET=x86_64-apple-darwin
    os: osx
    rust: stable
    script: cargo build --release --target $TARGET --locked
    install: true
    <<: *DEPLOY_TO_GITHUB
