[package]
name = "whiteboard"
version = "0.1.0"
authors = ["Julien Duranleau <jduranleau@cstj.qc.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
glutin = "0.24"