[package]
name = "inke"
version = "1.2.0"
authors = ["Julien Duranleau <julien.duranleau@gmail.com>"]
edition = "2018"

[dependencies]
gl = "0.14.0"
glutin = "0.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
